game/content/ghplots/dd_roadedge_propp.py

game/content/ghplots/dd_roadedge_propp.py: Add missing 'they' to data block of DZREPR_AngryAtSponsorship.

---

design/Mecha_Equipment.txt

The Charge mechanic makes melee mech actually fun instead of a waste of time.
Add some more melee weapons, including some Charge weapons.

design/Mecha_Equipment.txt: Add a handful more melee weapons.

---

game/geareditor.py
gears/base.py
history.txt

Prevent Integral weapons from being removed in the Mecha Engineering Terminal

---

game/chargen/lifepath.py

game/chargen/lifepath.py: Rename reference to Dominate Anima skill to Wildcraft

---

game/content/ghplots/dd_lancedev.py

game/content/ghplots/dd_lancedev.py: Correct missing reference to npc.

---

gears/aitargeters.py
gears/programs.py

This casts Haywire in a small area around the caster, affecting all units including allies and itself.
It might make sense to put `EMBlaster` to the Trailblazer: charge with the Trailblazer's Plasma Spear, then Localized EMP.

gears/programs.py: Add "Localized EMP" to EMBlaster.

---

gears/stats.py

gears/stats.py: Give a 'spot behind cover' action to Scouting.

---

gears/aitargeters.py
gears/base.py
gears/geffects.py
gears/stats.py

Implement Encourage action for Negotiation skill

---

game/combat/__init__.py

game/combat/__init__.py: Calls to get_skill_library should be in_combat = True.

---

game/fieldhq/__init__.py
game/fieldhq/fhqinfo.py

game/fieldhq/fhqinfo.py: Use longform display for items in fieldhq.

---

design/Haiho.txt

Combat against Haiho is unsatisfying because they currently sit
on an uncomfortable part of the design spectrum: less armored
than a BuruBuru, less agile than a Chameleon.
Enemy Haiho die just from the player looking at them funny.
Improve the armor, maintain mobility.

design/Haiho.txt: Improve Haiho longevity.

---

game/chargen/lifepath.py
gears/stats.py

Options to get cybertech skill.

Cybertech lifepath

---

gears/base.py

gears/base.py: Also tweak base trauma for other cyberware, given the change in base trauma calculation.

---

data/jobs_default.json
game/cyberdoc.py
gears/cyberinstaller.py
gears/selector.py

Fixes #94
Look!
See the selection bar at the right?  Yes, that's not the player character, it's a random lancemate, with a random Cyber Eye.

Random characters get cyberware

---

game/cyberdoc.py
gears/cyberinstaller.py

Kinda pointless currently since the shop code only adjusts the price if it is attached to an npc, but maybe future shop modifications can allow for e.g. black market shops with bigger discounts but which are gated by Criminal badge, or whatnot.

game/cyberdoc.py: Use the shop code for buy price calculations.

---

game/services.py

game/services.py: Prevent crash from using left/right keys in shop.

---

game/content/ghplots/dd_customobjectives.py
game/exploration.py
game/geareditor.py
gears/champions.py
gears/geffects.py
pbge/effects.py

First cut at creating a function that creates champions.
No missions that involve them yet, but you can look at what champions could be produced via the mecha editor, select the new "Edit Mecha Champion" entry.

Champions first cut

---

game/geareditor.py
history.txt

game/geareditor.py: Disallow installing Beings into cockpits.

---

game/content/ghwaypoints.py
game/cyberdoc.py
gears/base.py
gears/cyberinstaller.py

Cyberware on lancemates

---

game/cyberdoc.py

Because moving the mouse around to check how much you can afford and
how much the cyberware is, is annoying.

game/cyberdoc.py: Display credits in a persistent panel at bottom-left.

---

game/cyberdoc.py
game/services.py
game/shopui/__init__.py
game/shopui/actions.py
game/widgets.py
history.txt
pbge/widgets.py

Shop revamp

---

game/content/ghplots/dd_customobjectives.py

Those fights were practically impossible, forcing me to fight Zerosaikos, bleah.

game/content/ghplots/dd_customobjectives.py: Tone down the difficulty of 1v1 champion fights.

---

design/Chameleon.txt
design/Dielancer.txt
design/Mecha_Equipment.txt
design/PC_Equipment.txt
design/Zerosaiko.txt
gears/attackattributes.py
gears/base.py
gears/champions.py
gears/geffects.py
history.txt

New melee attribs

---

design/Daum.txt
gears/attackattributes.py
gears/base.py
gears/champions.py
history.txt

Because dual-wielding katars is so kewl.

Multiwield

---

design/BuruBuru.txt

Makes sense that the big sheet of metal can be used to smash into opponents.

design/BuruBuru.txt: Phalanx shields can now charge.

---

design/Musketeer.txt

With the increase in health, Musketeers, which are already at the edge of
their power supplies, are definitely not going to last even one battle.
Ameliorate with mild increase in engine and add an integral power source.

design/Musketeer.txt: Add batteries.

---

game/geareditor.py
gears/base.py

Implement 'Create New Mecha'

---

game/content/ghplots/dd_lancedev.py
game/services.py
gears/champions.py

Seems nice to do this since the lancemate mentions "custom gear", which is in-game speak for "champion" anyway.

Make champions-level shop, make Hermit Mechaniac a champion-level shop

---

game/content/ghplots/dd_roadedge_propp.py

game/content/ghplots/dd_roadedge_propp.py: Correct WhyDoYouNeedABigCannon, add load-time typechecking.

---

design/BuruBuru.txt
design/Chameleon.txt
design/Claymore.txt
design/Corsair.txt
design/Daum.txt
design/Gorilla.txt
design/Joust.txt
design/Kojedo.txt
design/Musketeer.txt
design/Petrach.txt
design/Phoenix.txt
design/Razer.txt
design/Secutor.txt
design/Thorshammer.txt
design/Trailblazer.txt
design/Ultari.txt
design/Zerosaiko.txt
gears/base.py
gears/geffects.py
history.txt

#181 suggests that missiles are severely underpowered.  This is an attempt to make missiles more relevant:
* More accuracy.
* Cannot be blocked with a shield, only intercepted.
* Interception made much less effective, but you can now stack multiple intercept weapons to improve interception.
* Much, much reduced cost.
* Increased the quantity of missiles of most mecha in general.

Improve missiles

---

game/combat/movementui.py
game/invoker.py
game/traildrawer.py

game/traildrawer.py: New module to draw the trail; now also shows where one action point ends.

---

game/content/ghplots/dd_lancedev.py
game/content/ghplots/dd_roadedge_propp.py
game/content/ghplots/lancemates.py
game/content/ghplots/tarot_cards.py
game/content/ghplots/tarot_reveal.py
game/content/ghplots/tarot_sockets.py
game/content/ghplots/utility.py
game/content/mechtarot.py
game/memobrowser.py
history.txt

This fixes an annoyance I have had with this game: I don't always go straight for the deadzone target, which sometimes means I have quests from multiple towns running.  Yes, my memo tells me Important Character is in Town Hall.  But Town Hall of ***which*** town???

game/memobrowser.py: Most memos now show their location.

---

design/Ultari.txt

design/Ultari.txt: Add Shockhauler Ultari.
